// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AMonthPicker: typeof import('ant-design-vue/es')['MonthPicker']
    AppLogo: typeof import('./src/components/Application/src/AppLogo.vue')['default']
    AppProvider: typeof import('./src/components/Application/src/AppProvider.vue')['default']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATree: typeof import('ant-design-vue/es')['Tree']
    AWeekPicker: typeof import('ant-design-vue/es')['WeekPicker']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
